<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>KE.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <AssemblyVersion>1.0.*</AssemblyVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <Deterministic>False</Deterministic>
        <GenerateAssemblyFileVersionAttribute>False</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyInformationalVersionAttribute>False</GenerateAssemblyInformationalVersionAttribute>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <Deterministic>False</Deterministic>
        <GenerateAssemblyFileVersionAttribute>False</GenerateAssemblyFileVersionAttribute>
        <GenerateAssemblyInformationalVersionAttribute>False</GenerateAssemblyInformationalVersionAttribute>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AoC.Core\AoC.Core.csproj" />
        <ProjectReference Include="..\AoC.Solutions\AoC.Solutions.csproj" />
    </ItemGroup>

</Project>
